name: Flutter Build

on:
  push:
    tags:
      - '*' # 监听所有标签
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin distribution
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # 设置 Flutter 版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK for Android
        run: flutter build apk --release


          # 创建 Release 并上传 APK
      - name: 上传 APK 到 Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false



#      - name: Upload APK
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-apk
#          path: android/app/build/outputs/apk/**/*.apk


#      - name: Upload APK to GitHub Releases
#        uses: softprops/action-gh-release@v1
#        with:
#          files: build/app/outputs/flutter-apk/app-release.apk
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build iOS
#        run: flutter build ios --release --no-codesign